spring.application.name=CMCmp3

spring.datasource.url=jdbc:mysql://localhost:3306/musicapp?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=01042005a5
spring.jpa.hibernate.ddl-auto=update         
spring.jpa.show-sql=true                
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# ? JWT CONFIGURATION (tu? ch?n)
# ===============================
jwt.secret=your-256-bit-secret-your-256-bit-secret
jwt.expiration=86400000                      

# ===============================
# ? SERVER CONFIGURATION
# ===============================
server.port=8080                            
server.error.include-message=always         

# ===============================
# ? OAUTH2 GOOGLE CONFIGURATION
# ===============================
spring.security.oauth2.client.registration.google.client-id=608691478747-7kabimscmqn5fmveh7qlhl26n52sk1nm.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# ===============================
# ? FILE UPLOAD CONFIGURATION
# ===============================
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===============================
# ? SPRING MAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cmcmp045@gmail.com
spring.mail.password=ohky skcq cytx zcsm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

firebase.service-account.path=classpath:firebase-service-account.json

firebase.bucket.name=cmcmp3-8e6f7.firebasestorage.app
