spring.application.name=smart-music-management

app.cors.allowed-origins=${FRONTEND_URL:http://localhost:3000}
app.frontend.url=${FRONTEND_URL:http://localhost:3000}

# Database
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT & Security
jwt.secret=${JWT_SECRET:your-256-bit-secret-your-256-bit-secret}
jwt.expiration=86400000

# Server
server.port=${SERVER_PORT:8080}
server.error.include-message=always

# OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# File Upload
file.upload-dir=E:/Downloads/temporary-files/smart-music-management-data
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Mail
spring.mail.protocol=smtp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Firebase
firebase.service-account.path=classpath:smart-music-management-firebase-service-config.json
firebase.bucket.name=${FIREBASE_BUCKET_NAME}

server.forward-headers-strategy=framework